import { Krona_One, DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./layout/Navbar";

const kronaOne = Krona_One({
  subsets: ["latin"],
  weight: "400", // Krona One has only 400
  variable: "--font-krona",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "DigiBhai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kronaOne.variable} ${dmSans.variable} ${inter.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
